import React, { useState } from "react";
import { useLocation } from "react-router-dom";

type ScreenConfig = {
  title: string;
  description: string;
  action: string;
  columns: string[];
  rows: string[][];
  stats: [string, string, string][];
  formTitle: string;
  formFields: string[];
};

const configs: Record<string, ScreenConfig> = {
  "/suppliers": { title: "Suppliers / Dairies", description: "Manage the dairies and suppliers you buy milk from.", action: "Add supplier", columns: ["Supplier", "Contact", "Milk purchased", "Outstanding", "Status"], rows: [["Shree Krishna Dairy", "98765 43210", "540 L", "₹31,414.00", "Active"], ["Malwa Milk Suppliers", "98123 45678", "160 L", "₹8,240.00", "Active"], ["Gokul Fresh Farms", "98980 11223", "80 L", "₹0.00", "Active"]], stats: [["Active suppliers", "12", "2 added this month"], ["Milk sourced this month", "4,820 L", "+8.4% vs last month"], ["Total payable", "₹31,414", "Across 3 open bills"]], formTitle: "Add a supplier", formFields: ["Supplier name", "Phone number", "Address"] },
  "/purchases": { title: "Milk Purchases", description: "Record incoming milk and track FAT-based purchase amounts.", action: "Record purchase", columns: ["Date", "Supplier", "Litres", "FAT", "Amount"], rows: [["12 Sept 2026", "Shree Krishna Dairy", "200 L", "6.5", "₹11,700.00"], ["05 Sept 2026", "Shree Krishna Dairy", "240 L", "6.4", "₹13,824.00"], ["03 Sept 2026", "Malwa Milk Suppliers", "160 L", "6.6", "₹9,504.00"], ["02 Sept 2026", "Shree Krishna Dairy", "200 L", "6.5", "₹11,700.00"]], stats: [["Today's milk", "240 L", "1 purchase entry"], ["This month's milk", "2,840 L", "From 4 suppliers"], ["Purchase value", "₹1,64,720", "This month"]], formTitle: "Record milk purchase", formFields: ["Supplier", "Quantity in litres", "FAT percentage"] },
  "/supplier-bills": { title: "Supplier Bills", description: "Review bills raised by your milk suppliers and settle outstanding balances.", action: "Create bill", columns: ["Bill no.", "Supplier", "Date", "Total", "Balance"], rows: [["SB-0042", "Shree Krishna Dairy", "05 Sept 2026", "₹27,524.00", "₹12,210.00"], ["SB-0041", "Malwa Milk Suppliers", "03 Sept 2026", "₹9,504.00", "₹8,240.00"], ["SB-0040", "Shree Krishna Dairy", "02 Sept 2026", "₹11,700.00", "₹11,700.00"]], stats: [["Open bills", "3", "Awaiting settlement"], ["Outstanding", "₹31,414", "Total payable"], ["Paid this month", "₹42,650", "5 settlements"]], formTitle: "Create supplier bill", formFields: ["Supplier", "Bill date", "Amount"] },
  "/customers": { title: "Customers", description: "Manage shops, sweet makers and other customers who buy your milk.", action: "Add customer", columns: ["Customer", "Contact", "Milk sold", "Outstanding", "Status"], rows: [["Sharma General Store", "98260 11223", "200 L", "₹14,200.00", "Active"], ["Patel Khowa Center", "97550 44789", "40 L", "₹1,340.00", "Active"], ["Anand Sweets", "98931 88776", "120 L", "₹3,520.00", "Active"]], stats: [["Active customers", "28", "4 added this month"], ["Milk sold this month", "3,180 L", "Across 22 customers"], ["Receivable", "₹19,060", "Total outstanding"]], formTitle: "Add a customer", formFields: ["Customer name", "Phone number", "Business address"] },
  "/sales": { title: "Milk Sales", description: "Record milk sales and keep customer deliveries up to date.", action: "Record sale", columns: ["Date", "Customer", "Litres", "Rate", "Amount"], rows: [["06 Sept 2026", "Sharma General Store", "200 L", "₹71.00", "₹14,200.00"], ["04 Sept 2026", "Patel Khowa Center", "40 L", "₹71.00", "₹2,840.00"], ["02 Sept 2026", "Anand Sweets", "120 L", "₹71.00", "₹8,520.00"]], stats: [["Today's milk sold", "0 L", "No sale entries today"], ["This month's sales", "3,180 L", "22 sale entries"], ["Sales value", "₹2,25,780", "At current rate"]], formTitle: "Record milk sale", formFields: ["Customer", "Quantity in litres", "Rate per litre"] },
  "/customer-bills": { title: "Customer Bills", description: "Track customer invoices and outstanding receivables.", action: "Create bill", columns: ["Bill no.", "Customer", "Date", "Total", "Balance"], rows: [["CB-0108", "Sharma General Store", "06 Sept 2026", "₹14,200.00", "₹14,200.00"], ["CB-0107", "Patel Khowa Center", "04 Sept 2026", "₹2,840.00", "₹1,340.00"], ["CB-0106", "Anand Sweets", "02 Sept 2026", "₹8,520.00", "₹3,520.00"]], stats: [["Open bills", "3", "With outstanding balance"], ["Receivable", "₹19,060", "Total from customers"], ["Collected this month", "₹28,500", "8 payments"]], formTitle: "Create customer bill", formFields: ["Customer", "Bill date", "Amount"] },
  "/payments": { title: "Payments / Ledger", description: "See every payment in one place and keep your cash ledger balanced.", action: "Record payment", columns: ["Date", "Party", "Type", "Reference", "Amount"], rows: [["05 Sept 2026", "Patel Khowa Center", "Customer", "CB-0107", "₹1,500.00"], ["04 Sept 2026", "Shree Krishna Dairy", "Supplier", "SB-0042", "₹15,314.00"], ["03 Sept 2026", "Anand Sweets", "Customer", "CB-0106", "₹5,000.00"]], stats: [["Money in", "₹28,500", "This month"], ["Money out", "₹42,650", "This month"], ["Net movement", "-₹14,150", "Supplier settlements"]], formTitle: "Record payment", formFields: ["Party", "Payment type", "Amount"] },
  "/adjustments": { title: "Adjustments", description: "Make controlled corrections for shortages, returns and other ledger changes.", action: "New adjustment", columns: ["Date", "Type", "Party", "Reason", "Amount"], rows: [["01 Sept 2026", "Credit", "Shree Krishna Dairy", "Can adjustment", "₹480.00"], ["28 Aug 2026", "Debit", "Patel Khowa Center", "Short delivery", "₹355.00"], ["22 Aug 2026", "Credit", "Anand Sweets", "Return", "₹710.00"]], stats: [["This month", "8", "Adjustments created"], ["Credits", "₹2,840", "Given to parties"], ["Debits", "₹1,420", "Recorded"]], formTitle: "Create adjustment", formFields: ["Party", "Adjustment type", "Amount"] },
  "/market-rates": { title: "Market Rates", description: "Set the active milk rate used for today’s sales and purchase calculations.", action: "Update rate", columns: ["Effective from", "Rate / litre", "Applied to", "Updated by"], rows: [["01 Aug 2026", "₹71.00", "All customers", "Subhash Kumar"], ["01 Jul 2026", "₹69.00", "All customers", "Subhash Kumar"], ["01 Jun 2026", "₹68.00", "All customers", "Subhash Kumar"]], stats: [["Current rate", "₹71.00/L", "Effective today"], ["Previous rate", "₹69.00/L", "From 01 Jul 2026"], ["Rate changes", "4", "This financial year"]], formTitle: "Update market rate", formFields: ["New rate per litre", "Effective from", "Notes"] },
  "/reports": { title: "Reports", description: "Understand your milk volume, cash flow and party balances at a glance.", action: "Export report", columns: ["Report", "Period", "Updated", "Format"], rows: [["Milk purchase summary", "September 2026", "Today, 09:30 AM", "PDF"], ["Customer sales report", "September 2026", "Today, 09:30 AM", "PDF"], ["Supplier outstanding report", "September 2026", "Yesterday", "CSV"]], stats: [["Purchase volume", "4,820 L", "This month"], ["Sales volume", "3,180 L", "This month"], ["Gross movement", "₹3,90,500", "Purchase + sales"]], formTitle: "Generate a report", formFields: ["Report type", "Start date", "End date"] },
  "/settings": { title: "Settings", description: "Configure the business profile and preferences for Subhash Dairy.", action: "Save changes", columns: ["Setting", "Current value", "Last updated"], rows: [["Business name", "Subhash Dairy", "01 Jan 2026"], ["Default unit", "Litres (L)", "01 Jan 2026"], ["Currency", "Indian Rupee (₹)", "01 Jan 2026"]], stats: [["Business name", "Subhash Dairy", "Active profile"], ["Default rate", "₹71.00/L", "Current market rate"], ["Data backup", "Up to date", "Last backup today"]], formTitle: "Business settings", formFields: ["Business name", "Owner name", "Phone number"] },
};

const Operations: React.FC = () => {
  const { pathname } = useLocation();
  const config = configs[pathname] || configs["/suppliers"];
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [query, setQuery] = useState("");
  const filteredRows = config.rows.filter(row => row.join(" ").toLowerCase().includes(query.toLowerCase()));

  return <div className="operations-page"><div className="page-heading"><div><p className="eyebrow">WORKSPACE <span>•</span> SEPTEMBER 2026</p><h1>{config.title}</h1><p>{config.description}</p></div><button className="primary-button" onClick={() => setIsFormOpen(true)}>+ <span>{config.action}</span></button></div><section className="operation-stats">{config.stats.map(([label, value, note]) => <article className="operation-stat" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section><section className="data-panel full-panel"><div className="panel-heading"><div><h2>{config.title} overview</h2><p className="panel-description">Showing {filteredRows.length} of {config.rows.length} records</p></div><label className="search-field">⌕<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search records" /></label></div><div className="table-wrap"><table><thead><tr>{config.columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{filteredRows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, cellIndex) => <td key={cellIndex} className={cellIndex === row.length - 1 ? "table-emphasis" : ""}>{cell}{cell === "Active" && <span className="status-dot" />}</td>)}</tr>)}</tbody></table></div></section><div className="screen-footer-note"><span>✦</span><p><b>Everything is in one place.</b> Use the action above to add a new record, or search this table to find an existing entry quickly.</p></div>{isFormOpen && <div className="modal-backdrop" onClick={() => setIsFormOpen(false)}><div className="entry-modal" onClick={event => event.stopPropagation()}><div className="modal-heading"><div><p className="eyebrow">NEW RECORD</p><h2>{config.formTitle}</h2></div><button className="modal-close" onClick={() => setIsFormOpen(false)}>×</button></div><form onSubmit={event => { event.preventDefault(); setIsFormOpen(false); }}><div className="form-grid">{config.formFields.map(field => <label key={field}>{field}<input placeholder={`Enter ${field.toLowerCase()}`} required /></label>)}</div><div className="modal-actions"><button type="button" className="cancel-button" onClick={() => setIsFormOpen(false)}>Cancel</button><button type="submit" className="primary-button">Save record</button></div></form></div></div>}</div>;
};

export default Operations;
